version: '3.8'
networks:
  carservice_default:
    driver: bridge
  monitoring:
    driver: bridge

services:
  # --- Frontend Service Definition ---
  frontend-service:
    networks:
      - carservice_default
    container_name: car-service-frontend
    build:
      context: ../CarServiceFrontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"

  # --- Backend Service Definition ---
  backend-service:
    networks:
    - carservice_default
    - monitoring
    container_name: car-service-backend
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/car_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"

  # --- PostgreSQL Database Service Definition ---
  postgres:
    networks:
      - carservice_default
      - monitoring
    image: postgres:16
    environment:
      POSTGRES_DB: car_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/:/etc/prometheus/ # Mount the config file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring # Add to the shared network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000' # Grafana's web interface port
    volumes:
      - grafana-data:/var/lib/grafana # Persistent storage for Grafana
    networks:
      - monitoring # Add to the shared network
    depends_on:
      - prometheus # Wait for Prometheus to be available
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=tizicravotta@gmail.com
      - GF_SMTP_PASSWORD=rmfgkcwxrlddilch
      - GF_SMTP_FROM_ADDRESS=tizicravotta@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alerts

  node-exporter: # Provides host metrics (CPU, RAM, disk)
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitoring # Add to the shared network


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080" # Using 8081 to avoid conflict with your backend
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
    networks:
      - monitoring # Add to the monitoring network

volumes:
  grafana-data:
  pgdata:





